@startuml
class OS
package "System" {

package "View JavaFx" {}
package "Control" {}
package "Helpers" {

class ConfigFileReader{
getLanguage()
setLanguage()
getDateFormat()
setDateFormat()
}

}

package "Model" {
class OsAdapter{
setDate()
getDate()
osPopUp()
}

OsAdapter -- OS


class Reminder{
date/time
}
class JPA{
readDb()
writeDb()
}
Reminder --OsAdapter
Reminder -- JPA

Remider --Notification
JavaFxPopUp--|>Notification
SystemPopUp--|>Notification
Email--|>Notification
IFTTTEvent--|>Notification
ShellScript--|>Notification

SystemPopUp -- OsAdapter
}
View -- Model
Model-- Control
Control -- "View JavaFx"

class ConfigFile{
language
timeFormat/localization
Db?
MailConfig?
}
ConfigFile--ConfigFileReader
View--ConfigFileReader
Reminder--ConfigFileReader
Reminder--Notification
}
JPA -- DB
DB <|.. Derby
DB <|.. MySQL
DB <|.. otherDB


OS--"cronjob/schtasks"
OS<|.. OSx
OS<|.. Windows10
OS<|.. Linux
Linux<|.. LinuxMint
Linux<|.. LinuxMintKDE
Linux<|.. Others
@enduml
