@startuml

package "System" {
Model -- View
View -- Control
Control --Model

package "View" {
class MainWindow
Interface Notification
Remider --Notification
JavaFxNotification--|>Notification
ConsoleNotification--|>Notification
}


package "Control" {
Class Controller
}
package "Helpers" {

class ConfigFileReader{
enableDarkMode
enableJavaFxNotification
enableConsoleNotification
enablePastRemindersNotification
enableImminentNotifications
enableRemindersThisMonth
}

}

package "Model" {



class Reminder{
subject
description
date
tags
}

Interface DbAdapter{
read()
write()
}
DbAdapter -- BinaryDbAdapter





@enduml
